apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-calculator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-calculator
  minReplicas: 1
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 10
        - type: Pods
          value: 8
          periodSeconds: 10
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 20
      policies:
        - type: Percent
          value: 100
          periodSeconds: 10
