apiVersion: v1
kind: Service
metadata: 
  name: flask-calculator-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: flask-calculator
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 5000
  